# Generated by Django 4.0.6 on 2023-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_category_options_alter_category_name_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
